package org.matt598.quantecoverwatch.utils;

public abstract class Format {
    public static String formatPortList(String[] ports){
        // Format the list of ports generated by LXDUtils.java into a JSON array.
        StringBuilder out = new StringBuilder();
        out.append("[");
        for(String port : ports){
            out.append("\""+port+"\",");
        }
        out.deleteCharAt(out.length()-1);
        out.append("]");
        return out.toString();
    }
}
